POST {{host}}/v1/accounts/confirm-change-email-by-token?$token=
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
Client-Signature: {{client_signature}}
Permanent-Language: {{permanent_language}}

{}